### ISSUE TITLE
"multiply_total" and "addition" operations considered invalid

### ISSUE THREAD

**Issue by StealthKokoro** [SnaveSutit/origins-mod-json-schemas#1]
multiply_total being not accepted is just flat out incorrect. my power works completely fine and as intended in-game.
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/95959212/c2349471-2955-40b2-afe5-03aaae2362e2)

i was also told the same for "addition," which is in an [example used on the wiki](https://origins.readthedocs.io/en/latest/types/power_types/modify_damage_taken/).

**Comment by SnaveSutit** [comment]
Technically, those are depreciated in the latest version of origins. But due to backwards compatibility it still functions. 
You can either use [one of these](https://origins.readthedocs.io/en/latest/types/data_types/attribute_modifier_operation/) for now (the recommended solution), or wait for me to add versioning to the schemas if you're using an older version of origins.

**Comment by SnaveSutit** [comment]
According to [this discord post on the origins server](https://discord.com/channels/734127708488859831/756024207883894814/1210136898803212328), I will be adding the legacy options to the schemas in the next release.

![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/28514936/6c7ac00b-2dde-4150-bcb4-2e40b2ab38a3)
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/28514936/35b6ae12-9639-42e2-8db3-c97976928f76)

**Comment by SnaveSutit** [comment]
Fixed in latest release
